### PR TITLE
Replace duplicate slide with missing slide and fix a link title

### PR DESCRIPTION
**Pull request by stackedsax**
Just noticed a little error: one of the slides from 2018 was duplicated.  Otherwise, looks very good.

### CODE REVIEW

**Comment by caniszczyk** [comment]
how is this duplicated in the README?

**Comment by stackedsax** [comment]
Lines 25-26:
```
### Challenges of Establishing an Open Source Program
![Challenges of Establishing an Open Source Program](chart-challenges-in-establishing-programs.png)
```

Lines 31-31 (the ones I am suggesting we remove):
```
### Challenges in Establishing Open Source Programs
![Challenges in Establishing Open Source Programs](chart-challenges-in-establishing-programs.png)
```

The only difference between those lines is one word in the heading: 'an'.  Otherwise, it's the same exact content and points to `chart-challenges-in-establishing-programs.png` in both places.

**Comment by stackedsax** [comment]
It looks like it's possible that one slide got left off: `chart-reasons-for-no-open-source-program.png`.

Happy to add that slide back in as a replacement for this duplicate entry.

**Comment by caniszczyk** [comment]
thanks, missed it when I first looked at it :)

**Comment by stackedsax** [comment]
No worries -- I added the slide back in and fixed another tiny thing in a link title.  Hope that's what you wanted!

**Pull request merged**
